CREATE TABLE `patientIntakeResponses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`age` int NOT NULL,
	`assessmentDate` date NOT NULL,
	`gender` varchar(50) NOT NULL,
	`hasDepression` boolean NOT NULL,
	`hasAnxiety` boolean NOT NULL,
	`hasPTSD` boolean NOT NULL,
	`takingMedication` boolean NOT NULL,
	`sadnessLevel` int NOT NULL,
	`anxietyLevel` int NOT NULL,
	`irritabilityLevel` int NOT NULL,
	`fatigueLevel` int NOT NULL,
	`motivationLevel` int NOT NULL,
	`enjoysMusic` boolean NOT NULL,
	`musicFrequency` varchar(50) NOT NULL,
	`musicGenres` text NOT NULL,
	`hasMusicalExperience` boolean NOT NULL,
	`hasFormalTraining` boolean NOT NULL,
	`trainingExperience` varchar(50),
	`musicSoothing` varchar(50) NOT NULL,
	`musicExpressesEmotions` varchar(50) NOT NULL,
	`opennessToMusicTherapy` varchar(50) NOT NULL,
	`totalScore` int NOT NULL,
	`passed` boolean NOT NULL,
	`status` enum('pending','approved','denied') NOT NULL DEFAULT 'pending',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `patientIntakeResponses_id` PRIMARY KEY(`id`)
);
